# -*- coding: utf-8 -*-
"""
Spyder Editor

This is a temporary script file.
"""

from datetime import datetime

# Initialize the variables
today = datetime.now()
selected_date = datetime.strptime("01/01/1900", "%m/%d/%Y")
selected_content = ""

year = today.year  # Get current year

# Initialize entryDate and entryContent
entryDate = []
entryContent = []

# Assuming entries are like this:
entries = [
    ("01/01", "1/1: Kalendae Ianuariae: Aesculapius, Vediovis"),
    ("01/02", "1/2: ante diem quartum Nonas Ianuarias"),
    ("01/03", "1/3: ante diem tertium Nonas Ianuarias: Compitalia"),
    ("01/04", "1/4: pridie Nonas Ianuarias"),
    ("01/05", "1/5: Nonae Ianuariae : Vica Pota"),
    ("01/06", "1/6: antediem octavum Idus Ianuarias"),
    ("01/07", "1/7: antediem septimum Idus Ianuarias"),
    ("01/08", "1/8: antediem sextum Idus Ianuarias"),
    ("01/09", "1/9: antediem quintum Idus Ianuarias: Agonalia"),
    ("01/10", "1/10: ante diem quartum Idus Ianuarias"),
    ("01/11", "1/11: ante diem tertium Idus Ianuarias: Carmentalia, Iuturnalia"),
    ("01/12", "1/12: pridie Idus Ianuarias"),
    ("01/13", "1/13: Idus Ianuariae"),
    ("01/14", "1/14: ante diem undecimum decimum Kalendas Februarias"),
    ("01/15", "1/15: ante diem duodevicesimum Kalendas Februarias: Carmentalia"),
    ("01/16", "1/16: ante diem septimum decimum Kalendas Februarias: Concordia"),
    ("01/17", "1/17: ante diem sextum decimum Kalendas Februarias"),
    ("01/18", "1/18: ante diem quintum decimum Kalendas Februarias"),
    ("01/19", "1/19: ante diem quartum decimum Kalendas Februarias"),
    ("01/20", "1/20: ante diem tertium decimum Kalendas Februarias"),
    ("01/21", "1/21: ante diem duodecimum Kalendas Februarias"),
    ("01/22", "1/22: ante diem undecimum Kalendas Februarias: Ludi Palatini"),
    ("01/23", "1/23: ante diem decimum Kalendas Februarias"),
    ("01/24", "1/24: ante diem nonum Kalendas Februarias: Paganalia"),
    ("01/25", "1/25: ante diem octavum Kalendas Februarias: Sementina"),
    ("01/26", "1/26: ante diem septimum Kalendas Februarias"),
    ("01/27", "1/27: ante diem sextum Kalendas Februarias: Dedicatio aedis Castorum"),
    ("01/28", "1/28: ante diem quintum Kalendas Februarias"),
    ("01/29", "1/29: ante diem quartum Kalendas Februarias"),
    ("01/30", "1/30: ante diem tertium Kalendas Februarias: Ara Pacis Augustae"),
    ("01/31", "1/31: pridie Kalendas Februarias"),
    ("02/01", "2/1: Kalendae Februariae : Iuno Sospita Mater Regina, Ceres"),
    ("02/02", "2/2: ante diem quartum Nonas Februarias"),
    ("02/03", "2/3: ante diem tertium Nonas Februarias"),
    ("02/04", "2/4: pridie Nonas Februarias"),
    ("02/05", "2/5: Nonae Februariae: Augustus Pater Patriae"),
    ("02/06", "2/6: ante diem octavum Idus Februarias"),
    ("02/07", "2/7: ante diem septimum Idus Februarias"),
    ("02/08", "2/8: ante diem sextum Idus Februarias"),
    ("02/09", "2/9: ante diem quintum Idus Februarias: Apollo"),
    ("02/10", "2/10: ante diem quartum Idus Februarias"),
    ("02/11", "2/11: ante diem tertium Idus Februarias"),
    ("02/12", "2/12: pridie Idus Februarias : Diana"),
    ("02/13", "2/13: Idus Februariae: Faunalia, Parentalia"),
    ("02/14", "2/14: ante diem sextum decimum Kalendas Martias: Iuno Februra"),
    ("02/15", "2/15: ante diem quintum decimum Kalendas Martias: Lupercalia"),
    ("02/16", "2/16: ante diem quartum decimum Kalendas Martias"),
    ("02/17", "2/17: ante diem tertium decimum Kalendas Martias: Quirinalia"),
    ("02/18", "2/18: ante diem duodecimum Kalendas Martias: Tacita"),
    ("02/19", "2/19: ante diem undecimum Kalendas Martias"),
    ("02/20", "2/20: ante diem decimum Kalendas Martias"),
    ("02/21", "2/21: ante diem nonum Kalendas Martias: Feralia"),
    ("02/22", "2/22: ante diem octavum Kalendas Martias: Caristia"),
    ("02/23", "2/23: ante diem septimum Kalendas Martias: Terminalia"),
    ("02/24", "2/24: ante diem sextum Kalendas Martias: Regifugium"),
    ("02/25", "2/25: ante diem quintum Kalendas Martias: Sementina"),
    ("02/26", "2/26: ante diem quartum Kalendas Martias"),
    ("02/27", "2/27: ante diem tertium Kalendas Martias: Equirria"),
    ("02/28", "2/28: pridie Kalendas Martias"),
    ("03/01", "3/1: Kalendae Martiae: Matronalia"),
    ("03/02", "3/2: ante diem sextum Nonas Martias"),
    ("03/03", "3/3: ante diem quintum Nonas Martias"),
    ("03/04", "3/4: ante diem quartum Nonas Martias"),
    ("03/05", "3/5: ante diem tertium Nonas Martias: Navigium Isidis"),
    ("03/06", "3/6: pridie Nonas Martias: Festum Vestae"),
    ("03/07", "3/7: Nonae Martiae"),
    ("03/08", "3/8: ante diem octavum Idus Martias"),
    ("03/09", "3/9: ante diem septimum Idus Martias"),
    ("03/10", "3/10: ante diem sextum Idus Martias"),
    ("03/11", "3/11: ante diem quintum Idus Martias"),
    ("03/12", "3/12: ante diem quartum Idus Martias"),
    ("03/13", "3/13: ante diem tertium Idus Martias"),
    ("03/14", "3/14: pridie Idus Martias: Equirria, Salii"),
    ("03/15", "3/15: Idus Martiae: Festum Annae Perennae, Attis"),
    ("03/16", "3/16: ante diem septimum decimum Kalendas Apriles: Mamuralia, Argei"),
    ("03/17", "3/17: ante diem sextum decimum Kalendas Apriles: Liberalia, Agonalia, Argei"),
    ("03/18", "3/18: ante diem quintum decimum Kalendas Apriles"),
    ("03/19", "3/19: ante diem quartum decimum Kalendas Apriles: Quinquatria"),
    ("03/20", "3/20: ante diem tertium decimum Kalendas Apriles: Quinquatria, Pelusia"),
    ("03/21", "3/21: ante diem duodecimum Kalendas Apriles: Quinquatria"),
    ("03/22", "3/22: ante diem undecimum Kalendas Apriles: Quinquatria, Festum Mangae Matris et Attidis, Hilaria"),
    ("03/23", "3/23: ante diem decimum Kalendas Apriles: Quinquatria, Hilaria, Tubilustrium"),
    ("03/24", "3/24: ante diem nonum Kalendas Apriles: Hilaria"),
    ("03/25", "3/25: ante diem octavum Kalendas Apriles: Hilaria"),
    ("03/26", "3/26: ante diem septimum Kalendas Apriles: Hilaria"),
    ("03/27", "3/27: ante diem sextum Kalendas Apriles: Hilaria"),
    ("03/28", "3/28: ante diem quintum Kalendas Apriles"),
    ("03/29", "3/29: ante diem quartum Kalendas Apriles"),
    ("03/30", "3/30: ante diem tertium Kalendas Apriles: Salus Publica, Concordia et Pax"),
    ("03/31", "3/31: pridie Kalendas Apriles: Luna"),
    ("04/01", "4/1: Kalendae Apriles: Venus Verticordia, Fortuna Virilis"),
    ("04/02", "4/2: ante diem quartum Nonas Apriles"),
    ("04/03", "4/3: ante diem tertium Nonas Apriles"),
    ("04/04", "4/4: pridie Nonas Apriles: Magna Mater, Ludi Megalenses"),
    ("04/05", "4/5: Nonae Apriles: Fortuna Publica, Ludi Megalenses"),
    ("04/06", "4/6: ante diem octavum Idus Apriles: Ludi Megalenses"),
    ("04/07", "4/7: ante diem septimum Idus Apriles: Ludi Megalenses"),
    ("04/08", "4/8: ante diem sextum Idus Apriles: Ludi Megalenses"),
    ("04/09", "4/9: ante diem quintum Idus Apriles: Ludi Megalenses"),
    ("04/10", "4/10: ante diem quartum Idus Apriles: Magna Mater, Ludi Megalenses"),
    ("04/11", "4/11: ante diem tertium Idus Apriles"),
    ("04/12", "4/12: pridie Idus Apriles: Ludi Ceriales"),
    ("04/13", "4/13: Idus Apriles: Iuppiter Victor, Ludi Ceriales"),
    ("04/14", "4/14: ante diem duodevicesimum Kalendas Maias: Ludi Ceriales"),
    ("04/15", "4/15: ante diem septimum decimum Kalendas Maias: Fordicidia, Ludi Ceriales"),
    ("04/16", "4/16: ante diem sextum decimum Kalendas Maias: Ludi Ceriales"),
    ("04/17", "4/17: ante diem quintum decimum Kalendas Maias: Ludi Ceriales"),
    ("04/18", "4/18: ante diem quartum decimum Kalendas Maias: Ludi Ceriales"),
    ("04/19", "4/19: ante diem tertium decimum Kalendas Maias: Cerialia, Ludi Ceriales"),
    ("04/20", "4/20: ante diem duodecimum Kalendas Maias"),
    ("04/21", "4/21: ante diem undecimum Kalendas Maias: Parilia, Natalis Romae"),
    ("04/22", "4/22: ante diem decimum Kalendas Maias"),
    ("04/23", "4/23: ante diem nonum Kalendas Maias: Vinalia Priora, Venus Ericina"),
    ("04/24", "4/24: ante diem octavum Kalendas Maias"),
    ("04/25", "4/25: ante diem septimum Kalendas Maias: Robigalia, Serapia"),
    ("04/26", "4/26: ante diem sextum Kalendas Maias"),
    ("04/27", "4/27: ante diem quintum Kalendas Maias"),
    ("04/28", "4/28: ante diem quartum Kalendas Maias: Floralia, Ludi Florales"),
    ("04/29", "4/29: ante diem tertium Kalendas Maias: Ludi Florales"),
    ("04/30", "4/30: pridie Kalendas Maias: Ludi Florales"),
    ("05/01", "5/1: Kalendae Maiae: Bona Dea, Laralia, Ludi Florales"),
    ("05/02", "5/2: ante diem sextum Nonas Maias : Ludi Florales"),
    ("05/03", "5/3: ante diem quintum Nonas Maias: Flora, Ludi Florales Circenses"),
    ("05/04", "5/4: ante diem quartum Nonas Maias"),
    ("05/05", "5/5: ante diem tertium Nonas Maias"),
    ("05/06", "5/6: pridie Nonas Maias"),
    ("05/07", "5/7: Nonae Maiae"),
    ("05/08", "5/8: ante diem octavum Idus Maias"),
    ("05/09", "5/9: ante diem septimum Idus Maias: Lemuria"),
    ("05/10", "5/10: ante diem sextum Idus Maias"),
    ("05/11", "5/11: ante diem quintum Idus Maias: Lemuria, Mania"),
    ("05/12", "5/12: ante diem quartum Idus Maias: Mars Ultor, Ludi Martis Circenses"),
    ("05/13", "5/13: ante diem tertium Idus Maias: Lemuria"),
    ("05/14", "5/14: pridie Idus Maias: Argei"),
    ("05/15", "5/15: Idus Maiae: Mercuralia"),
    ("05/16", "5/16: ante diem septimum decimum Kalendas Iunias"),
    ("05/17", "5/17: ante diem sextum decimum Kalendas Iunias: Dea Dia"),
    ("05/18", "5/18: ante diem quintum decimum Kalendas Iunias"),
    ("05/19", "5/19: ante diem quartum decimum Kalendas Iunias"),
    ("05/20", "5/20: ante diem tertium decimum Kalendas Iunias"),
    ("05/21", "5/21: ante diem duodecimum Kalendas Iunias: Agonalia"),
    ("05/22", "5/22: ante diem undecimum Kalendas Iunias"),
    ("05/23", "5/23: ante diem decimum Kalendas Iunias: Tubilustrium"),
    ("05/24", "5/24: ante diem nonum Kalendas Iunias"),
    ("05/25", "5/25: ante diem octavum Kalendas Iunias: Festum Fortunae publicae"),
    ("05/26", "5/26: ante diem septimum Kalendas Iunias"),
    ("05/27", "5/27: ante diem sextum Kalendas Iunias"),
    ("05/28", "5/28: ante diem quintum Kalendas Iunias"),
    ("05/29", "5/29: ante diem quartum Kalendas Iunias: Ambarvalia, Ludi Honoris et Virtutis"),
    ("05/30", "5/30: ante diem tertium Kalendas Iunias"),
    ("05/31", "5/31: pridie Kalendas Iunias"),
    ("06/01", "6/1: Kalendae Iuniae: Carnaria, Mars, Tempestas, Iuno Moneta"),
    ("06/02", "6/2: ante diem quartum Nonas Iunias"),
    ("06/03", "6/3: ante diem tertium Nonas Iunias: Bellona"),
    ("06/04", "6/4: pridie Nonas Iunias: Hercules Magnus Custos"),
    ("06/05", "6/5: Nonae Iuniae: Semo Sancus Dius Fidius"),
    ("06/06", "6/6: ante diem octavum Idus Iunias"),
    ("06/07", "6/7: ante diem septimum Idus Iunias: Piscatorii Ludi, Tiberinus"),
    ("06/08", "6/8: ante diem sextum Idus Iunias: Festum Mentis et Intellectus"),
    ("06/09", "6/9: ante diem quintum Idus Iunias: Festum Iovis Pistoris, Vestalia"),
    ("06/10", "6/10: ante diem quartum Idus Iunias: Festum Fortunae virilis"),
    ("06/11", "6/11: ante diem tertium Idus Iunias: Matralia, Fortuna"),
    ("06/12", "6/12: pridie Idus Iunias"),
    ("06/13", "6/13: Idus Iuniae: Festum Iovis Invicti, Quinquatrus Minores"),
    ("06/14", "6/14: ante diem duodevicesimum Kalendas Iulias: Quinquatrus Minores"),
    ("06/15", "6/15: ante diem septimum decimum Kalendas Iulias: Quinquatrus Minores"),
    ("06/16", "6/16: ante diem sextum decimum Kalendas Iulias"),
    ("06/17", "6/17: ante diem quintum decimum Kalendas Iulias"),
    ("06/18", "6/18: ante diem quartum decimum Kalendas Iulias"),
    ("06/19", "6/19: ante diem tertium decimum Kalendas Iulias: Minerva"),
    ("06/20", "6/20: ante diem duodecimum Kalendas Iulias: Dies Summani"),
    ("06/21", "6/21: ante diem undecimum Kalendas Iulias"),
    ("06/22", "6/22: ante diem decimum Kalendas Iulias"),
    ("06/23", "6/23: ante diem nonum Kalendas Iulias"),
    ("06/24", "6/24: ante diem octavum Kalendas Iulias: Dies Fortis Fortunae"),
    ("06/25", "6/25: ante diem septimum Kalendas Iulias: Ludi Taurei Quinquennales"),
    ("06/26", "6/26: ante diem sextum Kalendas Iulias: Ludi Taurei Quinquinnales"),
    ("06/27", "6/27: ante diem quintum Kalendas Iulias: Iuppiter Stator, Lares"),
    ("06/28", "6/28: ante diem quartum Kalendas Iulias"),
    ("06/29", "6/29: ante diem tertium Kalendas Iulias: Dies Quirini, Hercules Musarum"),
    ("06/30", "6/30: pridie Kalendas Iulias"),
    ("07/01", "7/1: Kalendae Iuliae: Iuno Felicitas"),
    ("07/02", "7/2: ante diem sextum Nonas Iulias"),
    ("07/03", "7/3: ante diem quintum Nonas Iulias"),
    ("07/04", "7/4: ante diem quartum Nonas Iulias"),
    ("07/05", "7/5: ante diem tertium Nonas Iulias: Poplifugia"),
    ("07/06", "7/6: pridie Nonas Iulias: Festum Fortunae muliebris, Ludi Apollinares"),
    ("07/07", "7/7: Nonae Iuliae : Nones Caprotinae , Ludi Apollinares, Palibus Duobus, Ancillarum Feriae, Consus"),
    ("07/08", "7/8: ante diem octavum Idus Iulias: Vitulatio, Ludi Apollinares"),
    ("07/09", "7/9: ante diem septimum Idus Iulias: Ludi Apollinares"),
    ("07/10", "7/10: ante diem sextum Idus Iulias: Ludi Apollinares"),
    ("07/11", "7/11: ante diem quintum Idus Iulias: Ludi Apollinares"),
    ("07/12", "7/12: ante diem quartum Idus Iulias: Ludi Apollinares"),
    ("07/13", "7/13: ante diem tertium Idus Iulias: Apollo, Ludi Apollinares"),
    ("07/14", "7/14: pridie Idus Iulias: Festum Fortunae muliebris"),
    ("07/15", "7/15: Idus Iuliae: Castor et Pollux, Honor et Virtus, Dies Equitum Romanorum"),
    ("07/16", "7/16: ante diem septimum decimum Kalendas Augustas"),
    ("07/17", "7/17: ante diem sextum decimum Kalendas Augustas: Honos / Victoria"),
    ("07/18", "7/18: ante diem quintum decimum Kalendas Augustas"),
    ("07/19", "7/19: ante diem quartum decimum Kalendas Augustas: Lucaria"),
    ("07/20", "7/20: ante diem tertium decimum Kalendas Augustas"),
    ("07/21", "7/21: ante diem duodecimum Kalendas Augustas: Lucaria, Ludi Victoriae Caesaris"),
    ("07/22", "7/22: ante diem undecimum Kalendas Augustas: Ludi Victoriae Caesaris, Concordia"),
    ("07/23", "7/23: ante diem decimum Kalendas Augustas: Neptunalia, Ludi Victoriae Caesaris"),
    ("07/24", "7/24: ante diem nonum Kalendas Augustas: Ludi Victoriae Caesaris"),
    ("07/25", "7/25: ante diem octavum Kalendas Augustas: Furrinalia, Ludi Victoriae Caesaris"),
    ("07/26", "7/26: ante diem septimum Kalendas Augustas: Ludi Victoriae Caesaris"),
    ("07/27", "7/27: ante diem sextum Kalendas Augustas: Ludi Victoriae Caesaris"),
    ("07/28", "7/28: ante diem quintum Kalendas Augustas: Ludi Victoriae Caesaris"),
    ("07/29", "7/29: ante diem quartum Kalendas Augustas: Ludi Victoriae Caesaris"),
    ("07/30", "7/30: ante diem tertium Kalendas Augustas: Ludi Victoriae Caesaris, Fortuna Diei"),
    ("07/31", "7/31: pridie Kalendas Augustas: Ludi Victoriae Caesaris"),
    ("08/01", "8/1: Kalendae Augustae: Festum Spei et Martis"),
    ("08/02", "8/2: ante diem quartum Nonas Augustas"),
    ("08/03", "8/3: ante diem tertium Nonas Augustas: Supplicia canum"),
    ("08/04", "8/4: pridie Nonas Augustas"),
    ("08/05", "8/5: Nonae Augustae: Festum Salutis"),
    ("08/06", "8/6: ante diem octavum Idus Augustas"),
    ("08/07", "8/7: ante diem septimum Idus Augustas"),
    ("08/08", "8/8: ante diem sextum Idus Augustas"),
    ("08/09", "8/9: ante diem quintum Idus Augustas: Sol Indiges"),
    ("08/10", "8/10: ante diem quartum Idus Augustas"),
    ("08/11", "8/11: ante diem tertium Idus Augustas"),
    ("08/12", "8/12: pridie Idus Augustas: Hercules Invictus, Venus Victrix, Hermes Invictus, Lychnapsia, Honor-Virtus-Felicitas"),
    ("08/13", "8/13: Idus Augustae: Hercules Victor, Diana, Flora, Castor et Pollux, Vertumnalia, Fortuna Equestri, Camenae"),
    ("08/14", "8/14: ante diem undevicesimum Kalendas Septembres"),
    ("08/15", "8/15: ante diem duodevicesimum Kalendas Septembres: Festum Astreae"),
    ("08/16", "8/16: ante diem septimum decimum Kalendas Septembres"),
    ("08/17", "8/17: ante diem sextum decimum Kalendas Septembres: Portunalia"),
    ("08/18", "8/18: ante diem quintum decimum Kalendas Septembres"),
    ("08/19", "8/19: ante diem quartum decimum Kalendas Septembres: Vinalia Rustica, Venus"),
    ("08/20", "8/20: ante diem tertium decimum Kalendas Septembres"),
    ("08/21", "8/21: ante diem duodecimum Kalendas Septembres: Consualia"),
    ("08/22", "8/22: ante diem undecimum Kalendas Septembres"),
    ("08/23", "8/23: ante diem decimum Kalendas Septembres: Volcanalia"),
    ("08/24", "8/24: ante diem nonum Kalendas Septembres: Luna, Mundus Patet"),
    ("08/25", "8/25: ante diem octavum Kalendas Septembres: Opiconsivia"),
    ("08/26", "8/26: ante diem septimum Kalendas Septembres"),
    ("08/27", "8/27: ante diem sextum Kalendas Septembres: Volturnia"),
    ("08/28", "8/28: ante diem quintum Kalendas Septembres: Festum Victoriae, Sol et Luna"),
    ("08/29", "8/29: ante diem quartum Kalendas Septembres"),
    ("08/30", "8/30: ante diem tertium Kalendas Septembres"),
    ("08/31", "8/31: pridie Kalendas Septembres"),
    ("09/01", "9/1: Kalendae Septembres: Natalis Telluris, Iuno Regina"),
    ("09/02", "9/2: ante diem quartum Nonas Septembres"),
    ("09/03", "9/3: ante diem tertium Nonas Septembres"),
    ("09/04", "9/4: pridie Nonas Septembres:"),
    ("09/05", "9/5: Nonae Septembres: Iuppiter Stator, Ludi Romani"),
    ("09/06", "9/6: ante diem octavum Idus Septembres: Ludi Romani"),
    ("09/07", "9/7: ante diem septimum Idus Septembres: Ludi Romani"),
    ("09/08", "9/8: ante diem sextum Idus Septembres: Ludi Romani"),
    ("09/09", "9/9: ante diem quintum Idus Septembres: Ludi Romani"),
    ("09/10", "9/10: ante diem quartum Idus Septembres: Ludi Romani"),
    ("09/11", "9/11: ante diem tertium Idus Septembres: Ludi Romani"),
    ("09/12", "9/12: pridie Idus Septembres: Ludi Romani"),
    ("09/13", "9/13: Idus Septembres: Epulum Iovis, Iuppiter Optimus Maximus, Ludi Romani"),
    ("09/14", "9/14: ante diem undevicesimum Kalendas Octobres: Ludi Romani"),
    ("09/15", "9/15: ante diem septimum decimum Kalendas Octobres: Ludi Romani"),
    ("09/16", "9/16: ante diem sextum decimum Kalendas Octobres: Ludi Romani"),
    ("09/17", "9/17: ante diem quintum decimum Kalendas Octobres: Ludi Romani"),
    ("09/18", "9/18: ante diem quartum decimum Kalendas Octobres: Ludi Romani"),
    ("09/19", "9/19: ante diem tertium decimum Kalendas Octobres: Ludi Romani"),
    ("09/20", "9/20: ante diem duodecimum Kalendas Octobres: Natalis Romuli"),
    ("09/21", "9/21: ante diem undecimum Kalendas Octobres"),
    ("09/22", "9/22: ante diem decimum Kalendas Octobres"),
    ("09/23", "9/23: ante diem nonum Kalendas Octobres: Natalis Augusti, Apollo, Ceres"),
    ("09/24", "9/24: ante diem octavum Kalendas Octobres"),
    ("09/25", "9/25: ante diem septimum Kalendas Octobres"),
    ("09/26", "9/26: ante diem sextum Kalendas Octobres: Venus Genetrix"),
    ("09/27", "9/27: ante diem quintum Kalendas Octobres: Festum Fortunae reducis"),
    ("09/28", "9/28: ante diem quartum Kalendas Octobres"),
    ("09/29", "9/29: ante diem tertium Kalendas Octobres"),
    ("09/30", "9/30: pridie Kalendas Octobres"),
    ("10/01", "10/1: Kalendae Octobres : Fides et Honor, Tigillum Sororium, Ceres"),
    ("10/02", "10/2: ante diem sextum Nonas Octobres"),
    ("10/03", "10/3: ante diem quintum Nonas Octobres: Ludi Divi Augusti et Fortunae Reducis"),
    ("10/04", "10/4: ante diem quartum Nonas Octobres: Ieiunium Cereris, Ludi Divi Augusti et Fortunae Reducis"),
    ("10/05", "10/5: ante diem tertium Nonas Octobres: Mundus Patet - Mania , Ludi Divi Augusti et Fortunae Reducis:"),
    ("10/06", "10/6: pridie Nonas Octobres: Ludi Divi Augusti et Fortunae Reducis"),
    ("10/07", "10/7: Nonae Octobres: Ludi Divi Augusti et Fortunae Reducis , Iuppiter Fulgur, Iuno Curitis"),
    ("10/08", "10/8: ante diem octavum Idus Octobres: Ludi Divi Augusti et Fortunae Reducis"),
    ("10/09", "10/9: ante diem septimum Idus Octobres: Apollo Palatinus, Fausta Felicitas, , Genius Publicus, Venus Victrix, Ludi Divi Augusti et Fortunae Reducis"),
    ("10/10", "10/10: ante diem sextum Idus Octobres: Ludi Divi Augusti et Fortunae Reducis, Iuno Moneta"),
    ("10/11", "10/11: ante diem quintum Idus Octobres: Meditrinalia, Ludi Divi Augusti et Fortunae Reducis"),
    ("10/12", "10/12: ante diem quartum Idus Octobres: Augustalia, Ludi Divi Augusti et Fortunae Reducis"),
    ("10/13", "10/13: ante diem tertium Idus Octobres: Fontinalia"),
    ("10/14", "10/14: pridie Idus Octobres: Penates Dei"),
    ("10/15", "10/15: Idus Octobres: Ludi Capitolini, October Equus"),
    ("10/16", "10/16: ante diem septimum decimum Kalendas Novembres"),
    ("10/17", "10/17: ante diem sextum decimum Kalendas Novembres"),
    ("10/18", "10/18: ante diem quintum decimum Kalendas Novembres"),
    ("10/19", "10/19: ante diem quartum decimum Kalendas Novembres: Armilustrium"),
    ("10/20", "10/20: ante diem tertium decimum Kalendas Novembres"),
    ("10/21", "10/21: ante diem duodecimum Kalendas Novembres"),
    ("10/22", "10/22: ante diem undecimum Kalendas Novembres"),
    ("10/23", "10/23: ante diem decimum Kalendas Novembres: Festum Liberi patris et Liberae"),
    ("10/24", "10/24: ante diem nonum Kalendas Novembres"),
    ("10/25", "10/25: ante diem octavum Kalendas Novembres"),
    ("10/26", "10/26: ante diem septimum Kalendas Novembres: Ludi Victoriae Sullanae"),
    ("10/27", "10/27: ante diem sextum Kalendas Novembres: Ludi Victoriae Sullanae"),
    ("10/28", "10/28: ante diem quintum Kalendas Novembres: Isia, Ludi Victoriae Sullanae"),
    ("10/29", "10/29: ante diem quartum Kalendas Novembres: Isia, Ludi Victoriae Sullanae, Festum Vertumni"),
    ("10/30", "10/30: ante diem tertium Kalendas Novembres: Isia, Ludi Victoriae Sullanae"),
    ("10/31", "10/31: pridie Kalendas Novembres: Isia, Ludi Victoriae Sullanae"),
    ("11/01", "11/1: Kalendae Novembres: Isia, Ludi Victoriae Sullanae"),
    ("11/02", "11/2: ante diem quartum Nonas Novembres: Isia"),
    ("11/03", "11/3: ante diem tertium Nonas Novembres: Hilaria, Isia"),
    ("11/04", "11/4: pridie Nonas Novembres: Ludi Plebei"),
    ("11/05", "11/5: Nonae Novembres: Ludi Plebei"),
    ("11/06", "11/6: ante diem octavum Idus Novembres: Ludi Plebei"),
    ("11/07", "11/7: ante diem septimum Idus Novembres: Ludi Plebei"),
    ("11/08", "11/8: ante diem sextum Idus Novembres: Mundus Patet - Mania, Ludi Plebei"),
    ("11/09", "11/9: ante diem quintum Idus Novembres: Ludi Plebei"),
    ("11/10", "11/10: ante diem quartum Idus Novembres: Ludi Plebei"),
    ("11/11", "11/11: ante diem tertium Idus Novembres: Ludi Plebei"),
    ("11/12", "11/12: pridie Idus Novembres: Ludi Plebei"),
    ("11/13", "11/13: Idus Novembres: Epulum Iovis, Feronia, Fortuna Primigenia, Pietas, Ludi Plebei"),
    ("11/14", "11/14: ante diem duodevicesimum Kalendas Decembres: Equorum Probatio, Ludi Plebei"),
    ("11/15", "11/15: ante diem septimum decimum Kalendas Decembres: Ludi Plebei"),
    ("11/16", "11/16: ante diem sextum decimum Kalendas Decembres: Ludi Plebei"),
    ("11/17", "11/17: ante diem quintum decimum Kalendas Decembres: Ludi Plebei"),
    ("11/18", "11/18: ante diem quartum decimum Kalendas Decembres: Mercatus, Ceres"),
    ("11/19", "11/19: ante diem tertium decimum Kalendas Decembres: Lectisternia Cybeles, Mercatus"),
    ("11/20", "11/20: ante diem duodecimum Kalendas Decembres: Mercatus"),
    ("11/21", "11/21: ante diem undecimum Kalendas Decembres"),
    ("11/22", "11/22: ante diem decimum Kalendas Decembres: Festum Plutonis et Proserpinae"),
    ("11/23", "11/23: ante diem nonum Kalendas Decembres"),
    ("11/24", "11/24: ante diem octavum Kalendas Decembres"),
    ("11/25", "11/25: ante diem septimum Kalendas Decembres"),
    ("11/26", "11/26: ante diem sextum Kalendas Decembres"),
    ("11/27", "11/27: ante diem quintum Kalendas Decembres"),
    ("11/28", "11/28: ante diem quartum Kalendas Decembres"),
    ("11/29", "11/29: ante diem tertium Kalendas Decembres"),
    ("11/30", "11/30: pridie Kalendas Decembres"),
    ("12/01", "12/1: Kalendae Decembres: Neptunus, Pietas, Festum Fortunae muliebris"),
    ("12/02", "12/2: ante diem quartum Nonas Decembres"),
    ("12/03", "12/3: ante diem tertium Nonas Decembres: Bona Dea, Ceres"),
    ("12/04", "12/4: pridie Nonas Decembres"),
    ("12/05", "12/5: Nonae Decembres: Faunalia Rustica"),
    ("12/06", "12/6: ante diem octavum Idus Decembres: Faunalia Rustica"),
    ("12/07", "12/7: ante diem septimum Idus Decembres: Faunalia Rustica"),
    ("12/08", "12/8: ante diem sextum Idus Decembres: Tiberinalia, Faunalia Rustica, Gaia"),
    ("12/09", "12/9: ante diem quintum Idus Decembres: Festum Iunonis iugalis"),
    ("12/10", "12/10: ante diem quartum Idus Decembres: Septimontium Agonalia"),
    ("12/11", "12/11: ante diem tertium Idus Decembres: Septimontium Agonalia, Sol Indiges, Ianus"),
    ("12/12", "12/12: pridie Idus Decembres: Consus, Septimontium Agonalia"),
    ("12/13", "12/13: Idus Decembres: Tellus"),
    ("12/14", "12/14: ante diem undevicesimum Kalendas Ianuarias"),
    ("12/15", "12/15: ante diem duodevicesimum Kalendas Ianuarias: Consualia, Fortuna Redux"),
    ("12/16", "12/16: ante diem septimum decimum Kalendas Ianuarias"),
    ("12/17", "12/17: ante diem sextum decimum Kalendas Ianuarias: Saturnalia"),
    ("12/18", "12/18: ante diem quintum decimum Kalendas Ianuarias: Saturnalia"),
    ("12/19", "12/19: ante diem quartum decimum Kalendas Ianuarias: Opalia, Saturnalia"),
    ("12/20", "12/20: ante diem tertium decimum Kalendas Ianuarias: Saturnalia"),
    ("12/21", "12/21: ante diem duodecimum Kalendas Ianuarias: Divalia, Angeronalia, Saturnalia, Hercules et Ceres"),
    ("12/22", "12/22: ante diem undecimum Kalendas Ianuarias: Saturnalia"),
    ("12/23", "12/23: ante diem decimum Kalendas Ianuarias: Larentalia, Sol Invictus, Brumaia, Saturnalia"),
    ("12/24", "12/24: ante diem nonum Kalendas Ianuarias"),
    ("12/25", "12/25: ante diem octavum Kalendas Ianuarias: Natalis Solis invicti"),
    ("12/26", "12/26: ante diem septimum Kalendas Ianuarias"),
    ("12/27", "12/27: ante diem sextum Kalendas Ianuarias"),
    ("12/28", "12/28: ante diem quintum Kalendas Ianuarias"),
    ("12/29", "12/29: ante diem quartum Kalendas Ianuarias"),
    ("12/30", "12/30: ante diem tertium Kalendas Ianuarias"),
    ("12/31", "12/31: pridie Kalendas Ianuarias"),

]

for date_str, content in entries:
    date = datetime.strptime(f"{date_str}/{year}", "%m/%d/%Y")
    entryDate.append(date)
    entryContent.append(content)

# Check if display variable is defined, if not, default it to 'date'
try:
    display
except NameError:
    display = 'date'

if display == 'random':
    import random
    selected_content = random.choice(entryContent)
else:
    for date, content in zip(entryDate, entryContent):
        if date <= today and date > selected_date:
            selected_content = content
            selected_date = date

print(selected_content)
